package com.example.taipeizoo.network.model

import com.google.gson.annotations.SerializedName

data class Plant(
    @SerializedName("_id") val id: Int,
    @SerializedName("_importdate") val importDate: ImportDate,
    @SerializedName("f_name_ch") val nameCh: String,
    @SerializedName("f_summary") val summary: String,
    @SerializedName("f_keywords") val keywords: String,
    @SerializedName("f_alsoknown") val alsoKnown: String,
    @SerializedName("f_geo") val geo: String,
    @SerializedName("f_location") val location: String,
    @SerializedName("f_name_en") val nameEn: String,
    @SerializedName("f_name_latin") val nameLatin: String,
    @SerializedName("f_family") val family: String,
    @SerializedName("f_genus") val genus: String,
    @SerializedName("f_brief") val brief: String,
    @SerializedName("f_feature") val feature: String,
    @SerializedName("f_function＆application") val functionAndApplication: String,
    @SerializedName("f_code") val code: String,
    @SerializedName("f_pic01_alt") val pic01Alt: String,
    @SerializedName("f_pic01_url") val pic01Url: String,
    @SerializedName("f_pic02_alt") val pic02Alt: String,
    @SerializedName("f_pic02_url") val pic02Url: String,
    @SerializedName("f_pic03_alt") val pic03Alt: String,
    @SerializedName("f_pic03_url") val pic03Url: String,
    @SerializedName("f_pic04_alt") val pic04Alt: String,
    @SerializedName("f_pic04_url") val pic04Url: String,
    @SerializedName("f_pdf01_alt") val pdf01Alt: String,
    @SerializedName("f_pdf01_url") val pdf01Url: String,
    @SerializedName("f_pdf02_alt") val pdf02Alt: String,
    @SerializedName("f_pdf02_url") val pdf02Url: String,
    @SerializedName("f_voice01_alt") val voice01Alt: String,
    @SerializedName("f_voice01_url") val voice01Url: String,
    @SerializedName("f_voice02_alt") val voice02Alt: String,
    @SerializedName("f_voice02_url") val voice02Url: String,
    @SerializedName("f_voice03_alt") val voice03Alt: String,
    @SerializedName("f_voice03_url") val voice03Url: String,
    @SerializedName("f_vedio_url") val videoUrl: String,
    @SerializedName("f_update") val update: String,
    @SerializedName("f_cid") val cid: String
) {
    fun generateZooItem(): ZooItem {
        return ZooItem(
            type = "PLANT",
            id = id,
            importDate = importDate,
            nameCh = nameCh,
            summary = summary,
            keywords = keywords,
            alsoKnown = alsoKnown,
            geo = geo,
            location = location,
            nameEn = nameEn,
            nameLatin = nameLatin,
            family = family,
            genus = genus,
            brief = brief,
            feature = feature,
            functionApplication = functionAndApplication,
            code = code,
            pic01Alt = pic01Alt,
            pic01Url = pic01Url,
            pic02Alt = pic02Alt,
            pic02Url = pic02Url,
            pic03Alt = pic03Alt,
            pic03Url = pic03Url,
            pic04Alt = pic04Alt,
            pic04Url = pic04Url,
            pdf01Alt = pdf01Alt,
            pdf01Url = pdf01Url,
            pdf02Alt = pdf02Alt,
            pdf02Url = pdf02Url,
            voice01Alt = voice01Alt,
            voice01Url = voice01Url,
            voice02Alt = voice02Alt,
            voice02Url = voice02Url,
            voice03Alt = voice03Alt,
            voice03Url = voice03Url,
            videoUrl = videoUrl,
            update = update,
            cid = cid
        )
    }
}
