package com.example.taipeizoo.network.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class ZooItem(
    val type: String,
    val id: Int,
    val importDate: ImportDate,
    val nameCh: String,
    val summary: String,
    val keywords: String,
    val alsoKnown: String,
    val geo: String,
    val location: String,
    val poigroup: String = "",
    val nameEn: String,
    val nameLatin: String,
    val phylum: String = "",
    val animalClass: String = "",
    val order: String = "",
    val family: String = "",
    val conservation: String = "",
    val distribution: String = "",
    val habitat: String = "",
    val feature: String,
    val behavior: String = "",
    val diet: String = "",
    val crisis: String = "",
    val interpretation: String = "",
    val themeName: String = "",
    val themeUrl: String = "",
    val adopt: String = "",
    val code: String,
    val genus: String = "",
    val brief: String = "",
    val functionApplication: String = "",
    val pic01Alt: String,
    val pic01Url: String,
    val pic02Alt: String,
    val pic02Url: String,
    val pic03Alt: String,
    val pic03Url: String,
    val pic04Alt: String,
    val pic04Url: String,
    val pdf01Alt: String,
    val pdf01Url: String,
    val pdf02Alt: String,
    val pdf02Url: String,
    val voice01Alt: String,
    val voice01Url: String,
    val voice02Alt: String,
    val voice02Url: String,
    val voice03Alt: String,
    val voice03Url: String,
    val videoUrl: String,
    val update: String,
    val cid: String
): Parcelable